services:
  postgres:
    image: postgres:16-alpine
    container_name: contexo_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contexo

volumes:
  postgres_data:
    name: contexo_postgres_data

networks:
  contexo:
    name: contexo-network
